### ISSUE TITLE
AbortError: GET can't be processed. Stream not writeable.

### ISSUE THREAD

**Issue by muhammadrizwanyaqub** [sagiegurari/multiple-redis#1]
I'm facing following issue while getting session from redis:

AbortError: GET can't be processed. Stream not writeable.
    at handle_offline_command (/home/dev/app/node_modules/redis/index.js:843:15)
    at RedisClient.internal_send_command (/home/dev/app/node_modules/redis/index.js:873:9)
    at RedisClient.get (/home/dev/app/node_modules/redis/lib/commands.js:62:25)
    at RedisClient.send_command.RedisClient.sendCommand (/home/dev/app/node_modules/redis/lib/extendedApi.js:45:26)
    at runRedisCommand (/home/dev/app/node_modules/multiple-redis/lib/multiple-redis.js:286:32)
    at /home/dev/app/node_modules/multiple-redis/node_modules/async/dist/async.js:3671:13
    at replenish (/home/dev/app/node_modules/multiple-redis/node_modules/async/dist/async.js:884:21)
    at iterateeCallback (/home/dev/app/node_modules/multiple-redis/node_modules/async/dist/async.js:869:21)
    at /home/dev/app/node_modules/multiple-redis/node_modules/async/dist/async.js:847:20
    at /home/dev/app/node_modules/multiple-redis/node_modules/async/dist/async.js:3676:17

Steps to reproduce:
Start 2 or more redis services and use them as clients with multiple-redis.
let's say, client1 running on port:6379 and client2 running on port:6380.
If both redis services are up and running, the session is stored and retrieved without any issue.
But if I stop first client (redis:6379), ideally it should ignore the error and should try to get data from next client and so on. Instead of continuing to the next client, it breaks the async series flow for getting data and returns the error. 

* **Version**: redis server 3.2.3, redis module 2.6.2, multiple-redis 0.0.76
* **Platform**: node 4.5.0 on CentOS 6.6

**Comment by sagiegurari** [comment]
will check it and get back to you.
sounds strange since it is kind of basic test I did a long time ago :)
maybe something changed with the redis client over time but I'll investigate and see.

**Comment by sagiegurari** [comment]
created a gist with a test:
https://gist.github.com/sagiegurari/c5ced2e10ccc1ce5e1abd09e5cda64cc
and ran it against 2 running redis servers.
than i killed one in the pause time in the middle of the test and i was able to fetch the value from the second redis.
I tested it with both running, both running and one killed before the get and both running and both get killed before the get.
only the last scenario shows an error which is as expected.
so... something is wrong on your end, and my guess is that none of the redis servers was actually available.

**Comment by muhammadrizwanyaqub** [comment]
Ok, let me confirm either my both redis instances were down or the only was one was down. I'll let you know.
