### ISSUE TITLE
Throws error if one of the instances is offline

### ISSUE THREAD

**Issue by AuspeXeu** [sagiegurari/multiple-redis#2]
#### Problem Description
I have the scenario, where I have configured two redis instances. One is local and one is remote to the machine. I use the redis client for a expressjs session store. When expressjs wants to store a session in the database and only one of the redis instances is up and running, an error as displayed below is thrown.

#### Code Example

````js
const MultipleRedis = require('multiple-redis')
const multiClient = MultipleRedis.createClient([{
    host: conf.get('redis_host'),
    port: conf.get('redis_port')
}, {
   host: '127.0.0.1',
   port: 6379,
}], {
  retry_strategy: () => 60 * 1000 //Every minute
})
const store = new RedisStore({
  client: multiClient,
  ttl: 7 * 24 * 60 * 60
})
````

#### Error Stack/Info (if any)

```
AbortError: GET can't be processed. Stream not writeable.
    at handle_offline_command (/opt/node_modules/redis/index.js:846:15)
    at RedisClient.internal_send_command (/opt/node_modules/redis/index.js:880:9)
    at RedisClient.get (/opt/node_modules/redis/lib/commands.js:62:25)
    at RedisClient.send_command.RedisClient.sendCommand (/opt/node_modules/redis/lib/extendedApi.js:45:26)
    at MultiRedisClient.invokeCommandOnClient (/opt/node_modules/multiple-redis/lib/multiple-redis.js:335:16)
    at runRedisCommand (/opt/node_modules/multiple-redis/lib/multiple-redis.js:426:22)
    at /opt/node_modules/multiple-redis/node_modules/async/dist/async.js:3853:24
    at replenish (/opt/node_modules/multiple-redis/node_modules/async/dist/async.js:946:17)
    at iterateeCallback (/opt/node_modules/multiple-redis/node_modules/async/dist/async.js:931:17)
    at /opt/node_modules/multiple-redis/node_modules/async/dist/async.js:906:16
    at /opt/node_modules/multiple-redis/node_modules/async/dist/async.js:3858:13
    at onWrappedCallback (/opt/node_modules/multiple-redis/lib/multiple-redis.js:281:13)
    at Command.onCommandEnd [as callback] (/opt/node_modules/multiple-redis/lib/multiple-redis.js:353:17)
    at normal_reply (/opt/node_modules/redis/index.js:721:21)
    at RedisClient.return_reply (/opt/node_modules/redis/index.js:819:9)
    at JavascriptRedisParser.returnReply (/opt/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/opt/node_modules/redis-parser/lib/parser.js:574:12)
    at Socket.<anonymous> (/opt/node_modules/redis/index.js:274:27)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
```

**Comment by sagiegurari** [comment]
that's kind of strange because it is a very basic scenario.
can you do the following change?

````js
const MultipleRedis = require('multiple-redis')
const multiClient = MultipleRedis.createClient([{
    host: conf.get('redis_host'),
    port: conf.get('redis_port')
}, {
   host: '127.0.0.1',
   port: 6379,
}], {
  retry_strategy: () => 60 * 1000 //Every minute
})

multiClient.once('connect', () => {
  const store = new RedisStore({
    client: multiClient,
    ttl: 7 * 24 * 60 * 60
  });

  //continue flow....
})
````

Reason is that I do not support offline mode to prevent old data issues and I push the following redis property:

````js
//disable offline queue to prevent old data in redis clients from being sent
if (options.enable_offline_queue === undefined) {
    options.enable_offline_queue = false;
}
````

So if you invoke some command when ALL redis clients are not available, you will get an error as it will not queue that command offline until a connection is established.
So when doing once('connect', ...) you ensure that you have at least 1 available redis connection.

**Comment by sagiegurari** [comment]
also can use the once('ready', ..) event like in the examples in the README.
tell me if it solves your issue

**Comment by AuspeXeu** [comment]
Hi @sagiegurari it does not seem to work properly. It seems like although I have the remote redis database as the first element in the config all writes are performed locally. I assumed the order is preserved during the setup process?

**Comment by sagiegurari** [comment]
order is preserved as you say.
for write, it goes in parallel so local would probably finish first although invoked differently based on the order you set.
for read, it goes in sequence one by one until it finds a value or until it went through all of them

**Comment by AuspeXeu** [comment]
Okay. I have to investigate this further. But it is definitely not working properly with the redistore for expressjs sessions right now.

**Comment by sagiegurari** [comment]
Ok. I have to admit I am using it daily and in production, but mostly for caching and pubsub.
As for express, at the past I used it for my redis store, but I moved to memory store so not sure exactly what might be the issue. When I did use it, it was working good.
Please keep me updated in this github issue when you find something in your env.

**Comment by AuspeXeu** [comment]
If you use it in the session middleware of expressjs it is quite hard to do it asynchronously. How did you set it when you used it?

**Comment by sagiegurari** [comment]
actually thats the simple part.
you first create the redis client, do once on 'ready' event and only than create the express + middlewares.

**Comment by AuspeXeu** [comment]
Yeah so you have to wait for the async execution with your entire setup. I assume there is no async version?

**Comment by sagiegurari** [comment]
Usually I got many async steps that I run before making my express available like loading data from DB, remote config and so on...
I don't want to get http requests before I finish those so I always setup the express after I finish to setup everything including async operations.

**Comment by AuspeXeu** [comment]
Alright, I have checked out my setup now. The write only happens to one of the two redis instances I have specified... i.e. the local one.

Local
![image](https://user-images.githubusercontent.com/2115696/28625529-6e41e7d0-7214-11e7-8b33-aa2aefe90ec3.png)

Remote
![image](https://user-images.githubusercontent.com/2115696/28625537-75a9300a-7214-11e7-843d-0cb3c568b421.png)

From my understanding, the sess:... should be written to both, no?

**Comment by sagiegurari** [comment]
it should write to both.
you can do redis-cli and than run the monitor command.
you will than see what commands are running for each redis server.
if specific redis server is not getting the commands executed it means something is wrong with the config or connectivity.

**Comment by AuspeXeu** [comment]
Yeah, so the monitoring shows that the remote instance does not get any messages. If I remove the local instance. I cannot establish a connection at all.

![image](https://user-images.githubusercontent.com/2115696/28626279-7931f8a4-7216-11e7-8492-631c488933a9.png)

However the ready event is fired. Plus I can connect via redis-cli command to the remote machine.

**Comment by AuspeXeu** [comment]
I think it works perfect now. Thanks! :)

**Comment by sagiegurari** [comment]
What did you change

**Comment by AuspeXeu** [comment]
I use the ready instead of the connect event now and have everything handled in a promise that resolves once the ready event is published.

**Comment by sagiegurari** [comment]
👍

**Comment by AuspeXeu** [comment]
Okay, I have no idea ... now I have this error again. I took the remote server offline to test the setup and all I get is this error. What the hell?!

```
AbortError: GET can't be processed. Stream not writeable.
    at handle_offline_command (/home/pi/www/node_modules/redis/index.js:846:15)
    at RedisClient.internal_send_command (/home/pi/www/node_modules/redis/index.js:880:9)
    at RedisClient.get (/home/pi/www/node_modules/redis/lib/commands.js:62:25)
    at RedisClient.send_command.RedisClient.sendCommand (/home/pi/www/node_modules/redis/lib/extendedApi.js:45:26)
    at MultiRedisClient.invokeCommandOnClient (/home/pi/www/node_modules/multiple-redis/lib/multiple-redis.js:335:16)
    at runRedisCommand (/home/pi/www/node_modules/multiple-redis/lib/multiple-redis.js:426:22)
    at /home/pi/www/node_modules/multiple-redis/node_modules/async/dist/async.js:3853:24
    at replenish (/home/pi/www/node_modules/multiple-redis/node_modules/async/dist/async.js:946:17)
    at /home/pi/www/node_modules/multiple-redis/node_modules/async/dist/async.js:950:9
    at eachOfLimit (/home/pi/www/node_modules/multiple-redis/node_modules/async/dist/async.js:975:24)
    at /home/pi/www/node_modules/multiple-redis/node_modules/async/dist/async.js:980:16
    at _parallel (/home/pi/www/node_modules/multiple-redis/node_modules/async/dist/async.js:3852:5)
    at Object.series (/home/pi/www/node_modules/multiple-redis/node_modules/async/dist/async.js:4708:5)
    at MultiRedisClient.invokeCommand (/home/pi/www/node_modules/multiple-redis/lib/multiple-redis.js:439:22)
    at RedisStore.get (/home/pi/www/node_modules/connect-redis/lib/connect-redis.js:149:18)
    at session (/home/pi/www/node_modules/express-session/index.js:460:11)
    at Layer.handle [as handle_request] (/home/pi/www/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/www/node_modules/express/lib/router/index.js:317:13)
    at /home/pi/www/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/pi/www/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/www/node_modules/express/lib/router/index.js:275:10)
    at /home/pi/www/node_modules/express-device/lib/device.js:46:26
```

**Comment by sagiegurari** [comment]
strange, I have a test case for 1 client failing and others not for a 'get' command:
https://github.com/sagiegurari/multiple-redis/blob/41aab0e67aac17d03cc672e7f7c8efbdd1373a48/test/spec/multiple-redis-spec.js#L861-L894
and I tested it a lot.

So from what it looks like, it is possible that in your case both redis servers failed?
and the fact I see 'handle_offline_command' in your stack leads me to believe that both redis clients are disconnected from your redis servers.
handle_offline_command is from the redis node library so if it goes there, you are not connected.
you can look at:
https://github.com/NodeRedis/node_redis/blob/master/index.js
Now, if both redis servers are disconnected, you will only get 1 error, so it doesn't matter which but it is clear that you are not connected.

I'm not sure what is going on in your machine (looks like raspberry pi, which is cool) but it looks unstable.
keep the monitor active on both redis servers while you are running to check what is going on (redis-cli than monitor command).
that is the only way you can see that the server doesn't die on your and to see exactly what commands you get for each server.

by the way, redis node client emits both connect and ready once a connection is opened (ready comes a bit later after the client lib gets the info on the redis).

**Comment by AuspeXeu** [comment]
Same test setup, remote is taken offline. This is the monitor on the local instance.

```
127.0.0.1:6379> MONITOR
OK
1501091139.595805 [0 127.0.0.1:50650] "info"
1501091143.478170 [0 127.0.0.1:50650] "get" "sess:BFwYt2jVXMLnonVoxbhBk4aZ_jptrogP"
```
Looks to me like the get is processed locally but still throws an error due to the remote instance being offline, no?

**Comment by sagiegurari** [comment]
let me double check again....

**Comment by AuspeXeu** [comment]
Might make a difference whether the instance was offline on creation of the multi-redis instance already or whether it goes offline afterwards?

**Comment by sagiegurari** [comment]
I was able to reproduce the issue. strange. i'm checking...

**Comment by sagiegurari** [comment]
FOUND IT.
well.... problem is that I'm not sure if there is a correct fix here or a fix at all....
Issue is as follows (from the test I was able to reproduce the issue)

* you create a multi client which than tries to connect to both redis servers
* once any redis client is ready, I emit ready since you should be able to work with 1 redis as well and I proxy all events for you from all clients.
* you set a value BUT second redis client is not ready yet so... you only able to set it in the first redis. but thats ok because you were able to set it at least in 1 redis
* you kill the first redis which well... has the value, second one is up but doesn't have any value
* you run get
* first redis is down, so I keep the error, second redis returns no value, so i return an error. if second redis would have returned a value, you would get a value and not an error.

So... issue is that you have 2 redis servers, but when doing the set you only had 1 available (redis client that is), and when doing get, the redis with the value was offline so no value to return.

what you could do in your code, is do on('ready', ...) and only once you get both of them ready to continue.
however, that is not a great solution so... what I'm planning to do is to add a new event 'all-ready' so you can listen to that with once and than continue.
what do you think?

**Comment by AuspeXeu** [comment]
Well, but what if one of the servers is offline on startup? The behaviour I would expect is that the redis client uses it's retry strategy to retry offline nodes to be able to reconnect to one of the servers that was not online at startup. Further I am not sure why you would throw an error. I am sure the normal redis client does not throw an error when you do a get which returns an empty set?!

**Comment by sagiegurari** [comment]
it does try to reconnect and it will reconnect.
issue is when you do set, you only have 1 redis available and 1 not and I do not hold offline queue (for a reason, I can explain the logic behind it, but basically it is because it can lead to huge issues), and than when you do get 1 server is down and 1 has no data. So returning no data or an error is basically the same and none help you, I could simply return the last redis server response (error or null) but it doesn't make more sense either (you have 2 responses, both bad, which one do you return?).

**Comment by AuspeXeu** [comment]
I would just return the same what the single redis client returns if you do get with a key he does not have?

**Comment by sagiegurari** [comment]
that would be null. I could do that.

**Comment by AuspeXeu** [comment]
Sounds reasonable

**Comment by sagiegurari** [comment]
In that scenario today you will get null

**Comment by AuspeXeu** [comment]
Let me know when there is a version I can test :)

**Comment by sagiegurari** [comment]
Probably later today

**Comment by sagiegurari** [comment]
please try now

**Comment by AuspeXeu** [comment]
I'll try it now. Does it also return null instead of throw an error?

**Comment by sagiegurari** [comment]
if 1 redis returns null and 1 error, it will return null.
it also has the all-ready event as well

**Comment by AuspeXeu** [comment]
I am updating right now

**Comment by AuspeXeu** [comment]
Seems to work so far so good. It seems tho that if the first redis in the sequence returns null for a get request, null is returned even though the second in line has the value.

**Comment by sagiegurari** [comment]
checking...

**Comment by sagiegurari** [comment]
in my test it looks like a value is returned.
got a test repo for that
https://github.com/sagiegurari/misc-test/tree/multi-redis

**Comment by sagiegurari** [comment]
wait... i'll recheck again

**Comment by sagiegurari** [comment]
can't reproduce that

**Comment by AuspeXeu** [comment]
Let me try to check it out with monitor

**Comment by sagiegurari** [comment]
sec...  maybe I found it...

**Comment by AuspeXeu** [comment]
Yeah. So it is definitely the case. I can see a get request on my remote server but it just came back online which means it does not have the value for that key. The local monitor shows that it never receives a get command.

**Comment by sagiegurari** [comment]
pushing a fix now.

**Comment by sagiegurari** [comment]
done. new version is now available.

**Comment by AuspeXeu** [comment]
Works flawless. Thank you very much for your patience 💯

**Comment by sagiegurari** [comment]
thank you for finding and testing the issues 👍

**Comment by AuspeXeu** [comment]
Btw just thinking about it now. Do you have a test case where initially all instances are online. Then you kill all of them (take them offline). What happens in that case if you try to `get`?

**Comment by sagiegurari** [comment]
I have such a test case. basically you will get an error if you do a get and all clients are disconnected.

**Comment by AuspeXeu** [comment]
Do you also have a test case in which the servers reconnect?

**Comment by sagiegurari** [comment]
Nothing to check there as the reconnect is not handled by me, it is handled by the redis lib itself
