### ISSUE TITLE
why do you use Redis Pubsub

### ISSUE THREAD

**Issue by MaryLilian** [sagiegurari/multiple-redis#26]
Hi, I am reading your project and I love this project
I have a question, why do you choose Redis Pubsub in your project instead of others like RabbitMQ or Kafka, are there any special features that others dont have it. Can you share me  it. I am wondering when I should choose Redis Pubsub instead of others like RabbitMQ or Kafka

**Comment by sagiegurari** [comment]
if redis lacks specific features you need, go with the alternatives. for me, redis had all pub/sub features i needed.
most importantly, i had redis in production for different reason (session store) so its better to reuse existing infrastructure for more use cases than start setting up more and more different components in production and making the entire architecture complex.
but, thats my opinion.
